name: masterclass

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install poetry
      uses: Gr1N/setup-poetry@v4
      
    - name: Disables creation of virtualenvs
      run: poetry config virtualenvs.create false
      
    - name: Install dependencies
      run: poetry install
      
    - name: run lint with black
      run: |
        make check
    
    - name: run test with ward
      run: |
        make test
